dotfiles_dir = "bombadil"

[settings]
vars = [ ]
# hooks = [ "echo 'asd' >> test_bomb " ]

[settings.dots]
awesome = { source = "awesome", target = ".config/awesome" }
alacritty = { source = "alacritty", target = ".config/alacritty" }
Xresources = { source = "Xresources", target = ".Xresources" }
p10k = { source = "p10k.zsh", target = ".p10k.zsh" }
zshrc = { source = "zshrc", target = ".zshrc" }
gitconfig = { source = "gitconfig", target = ".gitconfig" }
tmux-conf = { source = "tmux.conf", target = ".tmux.conf" }
tmux= { source = "tmux", target = ".tmux" }
wal = { source = "wal", target = ".config/wal" }
nvim = { source = "nvim", target = ".config/nvim" }
picom = { source = "picom", target = ".config/picom" }
dunst = { source = "dunst", target = ".config/dunst" }
uGet = { source = "uGet", target = ".config/uGet" }
QtProject = { source = "QtProject.conf", target = ".config/QtProject.conf" }
remmina-prefs = { source = "remmina-pref", target = ".config/remmina" }
remmina-items = { source = "remmina-items", target = ".local/share/remmina" }
