dotfiles_dir = "bombadil"

[settings]
vars = [ ]
hooks = [ "zsh -c \"ln -s $HOME/.cache/wal/colors.lua $HOME/.config/awesome/themes/my_theme/pywal.lua\"" ]

[settings.dots]
awesome = { source = "awesome", target = ".config/awesome" }
alacritty = { source = "alacritty", target = ".config/alacritty" }
Xresources = { source = "Xresources", target = ".Xresources" }
p10k = { source = "p10k.zsh", target = ".p10k.zsh" }
zshrc = { source = "zshrc", target = ".zshrc" }
gitconfig = { source = "gitconfig", target = ".gitconfig" }
tmux-conf = { source = "tmux.conf", target = ".tmux.conf" }
tmux= { source = "tmux", target = ".tmux" }
wal = { source = "wal", target = ".config/wal" }
nvim = { source = "nvim", target = ".config/nvim" }
picom = { source = "picom", target = ".config/picom" }
dunst = { source = "dunst", target = ".config/dunst" }
uGet = { source = "uGet", target = ".config/uGet" }
QtProject = { source = "QtProject.conf", target = ".config/QtProject.conf" }
remmina-prefs = { source = "remmina-pref", target = ".config/remmina" }
remmina-items = { source = "remmina-items", target = ".local/share/remmina" }
rofi = { source = "rofi", target = ".config/rofi" }
vscodium = { source = "vsc", target = ".config/VSCodium"}
gtkrc2 = { source = "gtk/gtkrc2", target = ".config/gtkrc-2.0"}
gtkrc3 = { source = "gtk/gtkrc", target = ".config/gtkrc"}
gtk2 = { source = "gtk/gtk2", target = ".config/gtk-2.0"}
gtk3 = { source = "gtk/gtk3", target = ".config/gtk-3.0"}
lock = { source = "lock.sh", target = ".config/lock.sh" }
wallpaper = { source = "wallpaper.sh", target = "wallpaper.sh" }
code = {source="code", target = ".config/code"}
dwm = { source = "dwm.sh", target = "dwm.sh"}
polybar = { source = "polybar", targer = ".config/polybar" }
powermenu = { source = "powermenu.sh", target = "powermenu.sh" }

#  need to add .cache/wal to this so that the color schemes can work on the new system, and do not break vim,
#  zsh, awesome, rofi etc
